### PR TITLE
Fix move nav

### PR DESCRIPTION
**Pull request by qnix**
When playing / stepping through a PGN, `pygn-mode-next-move` might skip one or more moves in certain cases:
- The move is a pawn capture, e.g., `cxd4`.
- This PGN fragment: `1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O Be7 6. Re1 b5 7. Bb3 O-O 8. c3 d5 ` 
   If you place the cursor on '5'  (the start of "5. O-O") and invoke next-move. "O-O" is not shown as the next move.

The pull request fixes these issue.

The side effect of this change is that when you reach the end (for next-move), or beginning (for previous-move) of a game, you will nolonger get the error message indicating there is no more move -- which is annoying in my opinion.

The change also simplify the next-move previous-move logic, and make the code more direct.

Visually, when doing next-move, the cursor will landed on the last character of the move.  And when doing previous-move, the cursor landed on the beginning of the move.

### CODE REVIEW

**Comment by rolandwalker** [comment]
Hi!  Thanks, and thanks for revising!

This PR still does too many things at once, some of which are desirable, and some of which are not.

The diagnosis of skipping over pawn captures and castles is correct — thanks — and also applies to pawn promotions.  @dwcoates had noticed the skipping but we hadn't tracked it down.

Just the fix for pawn captures in `pygn-mode--strict-legal-move-pat` would be great in a separate PR, if you are willing: `\\(?:[a-h]x?\\)?[a-h][1-8]` .

The fix for skipping over castles should actually be changing these ranges from A-Za-z to `a-h`:
https://github.com/dwcoates/pygn-mode/blob/503ebb29de55d90e60bc7682f821d915cdbd0ae4/pygn-mode.el#L651-L660 .  I cannot remember why I wrote A-Za-z in the first place.

Some of the other things this PR does include
* changing the location of the point when navigating moves
* removing the feature of skipping over variations by default
* changing `pygn-mode--relaxed-legal-move-pat` even though that pattern remained unused in the changed code
* including annotations as a part of `pygn-mode--strict-legal-move-pat`, which is intended to be "strict"
* removing the message when there are no more moves

most of which would be better in a local defun if these are your preferences.  Did you diagnose a separate problem with annotations?  Let us know.

Ultimately the plan is to use https://github.com/rolandwalker/tree-sitter-pgn for both highlighting and navigation, which will be a lot more straightforward than regexes.

**Review by rolandwalker — CHANGES_REQUESTED** [review]
Requested changes: just pawn captures.

**Comment by rolandwalker** [comment]
Side note: usages of `\s-` in the original code may be incorrect, or incorrectly escaped, and need to be checked.

**Comment by qnix** [comment]
I see.  I haven't used the `comment` and `variation` features and totally missed that.  I will rework the pull request to fix the skipping only focus on the regexp.

**Comment by qnix** [comment]
In case you missed this commit message:

```
Found this example where after 49. h8=Q, it doesn't land on 49...Rxh8

1. e4 e5 2. Nc3 Bc5 3. g3 h5 4. h3 h4 5. g4 Ne7 6. d3 Ng6 7. Be3 d6
8. Qd2 Be6 9. Nge2 Nc6 10. f4 Bxe3 11. Qxe3 exf4 12. Nxf4 Qg5 13. Nfd5
Qxe3+ 14. Nxe3 Nd4 15. O-O-O Kd7 16. Ne2 Nf3 17. Bg2 Ng5 18. d4 f6
19. Nf5 Bxf5 20. exf5 Ne7 21. Nf4 c6 22. c4 Rae8 23. Rhe1 b6 24. Ne6
Nc8 25. Nxg7 Rxe1 26. Rxe1 c5 27. dxc5 dxc5 28. Ne6 Nd6 29. b3 Rg8
30. Nxg5 Rxg5 31. Bd5 b5 32. Re6 bxc4 33. bxc4 Nxf5 34. gxf5 Rxf5
35. Re4 Rf2 36. a4 Ra2 37. Rxh4 Rxa4 38. Rf4 Ke7 39. h4 Ra2 40. Be4
Rh2 41. Bg6 Kd6 42. h5 Ke5 43. Re4+ Kd6 44. Re8 Rh4 45. Kb2 f5 46. Rf8
Rxc4 47. h6 Rh4 48. h7 Kc6 49. h8=Q Rxh8 50. Rxh8 Kd5 51. Bxf5 a5
52. Bc2 Kc4 53. Rh4+ Kb5 54. Ba4+ Kb6 55. Kc3 c4 56. Kxc4 Kb7 57. Kb5
Kb8 58. Rh7 1-0

but it has no problem with 50. Rxh8 (the very next move with the same
textual representation - Rxh8). So it appears there are a bug some
where else in the scanning code.
```

**Comment by rolandwalker** [comment]
Yes, changing the ranges elsewhere from A-Za-z to a-h fixes skipping over castling and promotions.

**Comment by qnix** [comment]
> Yes, changing the ranges elsewhere from A-Za-z to a-h fixes skipping over castling and promotions.

You are right.  Sorry I didn't think about that after reading your earlier comments.

**Comment by qnix** [comment]
Not sure why the test fail.

**Comment by dwcoates** [comment]
> Not sure why the test fail.

I believe it's failing lint because your last PR featured an unused variable `val-string`. I missed this when I merged it. It's not a big deal; if that that unused variable, tests might pass again.

**Comment by qnix** [comment]
Found an issue with long castles in this game:

1. e4 c6 2. Nc3 d5 3. Nf3 dxe4 4. Nxe4 Nf6 5. Qe2 Nxe4 6. Qxe4 Nd7 7. Bc4 e6 8. d4 Nf6 9. Qe2 Bd6 10. Bg5 a6 11. O-O-O Qc7 12. Kb1 Bd7 13. Ne5 Rf8 14. Rhe1 O-O-O 15. Rd3 Kb8 16. Rb3 Ka7 17. Qf3 Be7 18. Bf4 Bd6 19. Bg3 Nd5 20. Qh5 Bc8 21. Qxh7 Nb6 22. Qxg7 f6 23. Qxc7 Bxc7 24. Ng6 Bxg3 25. Rxg3 Nxc4 26. Nxf8 Rxf8 27. b3 Nd6 28. Kb2 Kb6 29. c4 Kc7 30. Rg7+ Bd7 31. Rxe6 Nf5 32. Rh7 Nxd4 33. Ree7 Rd8 34. h4 Nf5 35. Ref7 b6 36. Rxf6 1-0

On the board, it first shows short castle, and then on subsequent next-move shows long castle.

Added another change to the strict san regexp.

**Review by rolandwalker — APPROVED** [review]

**Comment by rolandwalker** [comment]
Thanks very much for the revisions!

**Pull request merged**
