### PR TITLE
Bundle Python chess library version 1.6.1

### PR DESCRIPTION
**Pull request by rolandwalker**
This works if you have checked out the whole repo.

MELPA will need some special instructions in order to include the python files with an install.

There is no problem of license incompatibility because we are distributing the `chess` library intact, with source and license, and not linking with it.

### CODE REVIEW

**Comment by dwcoates** [comment]
Might be nice to update the `.gitattributes` file to exclude python chess

**Comment by rolandwalker** [comment]
What do you mean?

**Comment by dwcoates** [comment]
The language summary will be dominated by python-chess  (it'll say our repository is all Python)
Screenshot from 2021-06-17 10-14-52

**Comment by dwcoates** [comment]
Adding a `.gitattributes` file at root with 
```
lib/*   linguist-vendored
```
should fix so github ignores it

**Comment by rolandwalker** [comment]
Done.

**Review by dwcoates — APPROVED** [review]

**Pull request merged**
